export const PERMISSIONS = {
  HOME_VIEW: "home.view",
  PROFILE_VIEW: "planning.create.view",
  SETTINGS_VIEW: "settings.view",
  USER_MANAGEMENT_VIEW: "user-management.view",
  USER_MANAGEMENT_CREATE: "user-management.create",
  USER_MANAGEMENT_EDIT: "user-management.edit",
  USER_ACCESS_ASSIGN: "user-access.assign",
  MACHINE_VIEW: "machine.view",
  MACHINE_LIST_VIEW: "machine.view",
  CUSTOMER_VIEW: "customer.view",
  CUSTOMER_LIST_VIEW: "customer.view",
  VENDOR_VIEW: "vendor.view",
  VENDOR_LIST_VIEW: "vendor.view",
  FABRIC_VIEW: "fabric.view",
  FABRIC_LIST_VIEW: "fabric.view",
  CONSTRUCTION_VIEW: "construction.view",
  CONSTRUCTION_LIST_VIEW: "construction.view",
  PROCESS_VIEW: "process.view",
  PROCESS_LIST_VIEW: "process.view",
  WIDTH_VIEW: "width.view",
  WIDTH_LIST_VIEW: "width.view",
  SFINISHING_VIEW: "sfinishing.view",
  FINISHING_LIST_VIEW: "sfinishing.view",
  FINISHING_CREATE: "finishing.create",
  GREYENTRY_VIEW: "greyentry.view",
  GREYENTRY_CREATE: "greyentry.create",
  GREYENTRY_EDIT: "greyentry.edit",
  GREYENTRY_DELETE: "greyentry.delete",
  GREYENTRY_RETURN: "greyentry.return",
  GREYENTRY_PRINT: "greyentry.print",

  PLANNING_CREATE: "planning.create.view",
  PLANNING_VIEW: "planning.view",
  PLANNING_PRINT: "planning.print.view",
  PLANNING_EXPORT: "planning.export",
  PLANNING_DELETE: "planning.delete",

  BATCH_CREATE: "batch.create.view",

  LABENTRY_VIEW: "labentry.view",
  LABENTRY_CREATE: "labentry.create",
  LABENTRY_EDIT: "labentry.edit",

  BATCH_VIEW: "batch.view",
  BATCH_DETAILS_VIEW: "batch.details.view",
  BATCH_EDIT_VIEW: "batch.edit.view",

  STOREENTRY_VIEW: "storeentry.view",

  DELIVERY_VIEW: "delivery.view",
  DELIVERY_CREATE: "delivery.create.view",
  DELIVERY_PRINT: "delivery.print.view",
  DELIVERY_EXPORT: "delivery.export",
  DELIVERY_DELETE: "delivery.delete",

  FINISHING_VIEW: "finishing.view",
  FINISHING_PRINT: "finishing.print",
  FINISHING_COMPLETE: "finishing.complete",
  FINISHING_DELETE: "finishing.delete",

  PSTOCK_VIEW: "pstock.view",
  PSTOCK_CREATE: "pstock.create",
  PSTOCK_RETURN: "pstock.return",
  PSTOCK_PRINT: "pstock.print",

  BSTOCK_VIEW: "bstock.view",
  BSTOCK_CREATE: "bstock.create",
  BSTOCK_EDIT: "bstock.edit",
  BSTOCK_DELETE: "bstock.delete",

  INVOICE_CREATE_VIEW: "invoice.create.view",
  INVOICE_LIST_VIEW: "invoice.list.view",
  INVOICE_PRINT: "invoice.print.view",
  INVOICE_EXPORT: "invoice.export",

  RETURN_VIEW: "return.view",

  REPORTS_VIEW: "reports.view",

  PURCHASE_ORDER_VIEW: "purchase-order.view",
  PURCHASE_ORDER_LIST_VIEW: "purchase-order.list.view",
  PURCHASE_ORDER_EDIT_VIEW: "purchase-order.edit.view",
  PURCHASE_ORDER_PRINT_VIEW: "purchase-order.print.view",

  MRS_VIEW: "mrs.view",
  MRS_CREATE: "mrs.create",

  PROCESS_ROUTE_VIEW: "processroute.view",

  USERS_VIEW: "users.view",
  USERS_EDIT_VIEW: "users.edit.view",
  USERS_CREATE_VIEW: "users.create.view",
  USERS_DELETE_VIEW: "users.delete.view",

  CUSTOMER_CREATE: "customer.create.view",
  CUSTOMER_EDIT: "customer.edit.view",
  CUSTOMER_DELETE: "customer.delete",
  CUSTOMER_PRINT: "customer.print.view",
  CUSTOMER_EXPORT: "customer.export",

  BATCH_EDIT: "batch.edit.view",
  BATCH_DELETE: "batch.delete",
  BATCH_PRINT: "batch.print.view",
  BATCH_EXPORT: "batch.export",
  BATCH_COMPLETE: "batch.complete",

  SETTINGS_MENU_LISTS: {
    MACHINE: "machine.view",
    USERS: "user-management.view",
    USER_ACCESS: "user-management.view",
    CUSTOMER: "customer.view",
    FABRIC: "fabric.view",
    CONSTRUCTION: "construction.view",
    VENDOR: "vendor.view",
    PROCESS: "process.view",
    WIDTH: "width.view",
    FINISHING: "sfinishing.view",
  },
};
